
# MySql Configurations
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/foodorderingsystem
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



#main:
#allow-circular-references: true

#Server Configuration
server:
    port: 9090



 